# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # 定时构建，每周一、五凌晨三点触发
  schedule:
    - cron: '0 3 * * 1,5'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # 设置java
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: |
              8
              11
              17
              21

      # 安装git（不太确定git有没有预装）
      # - name: install git
      #   run: su root && apt-get install git

      # 设置git名称和邮箱（虽然不是真的）
      - name: setup git
        run: git config --global user.email "123@123.123" && git config --global user.name "123"

      # 克隆仓库
      - name: clone repo
        run: |
          git clone https://github.com/PaperMC/Paper
          git clone https://github.com/PaperMC/Folia
          git clone https://github.com/LeavesMC/Leaves
          git clone https://github.com/pufferfish-gg/Pufferfish
          git clone https://github.com/PurpurMC/Purpur
          git clone https://github.com/CraftCanvasMC/Canvas
          git clone https://github.com/Winds-Studio/Leaf

      # 构建paper
      - name: build paper
        run: |
          cd Paper
          ./gradlew applypatches
          ./gradlew createReobfBundlerJar
          ./gradlew createMojmapBundlerJar

      # 构建folia
      - name: build folia
        run: |
          cd Folia
          ./gradlew applypatches
          ./gradlew createReobfBundlerJar
          ./gradlew createMojmapBundlerJar

      # 构建pufferfish
      - name: build pufferfish
        run: |
          cd Pufferfish
          ./gradlew applypatches
          ./gradlew createReobfBundlerJar
          ./gradlew createMojmapBundlerJar
          
      # 构建purpur
      - name: build purpur
        run: |
          cd Purpur
          ./gradlew applypatches
          ./gradlew createReobfBundlerJar
          ./gradlew createMojmapBundlerJar

      # 构建canvas
      - name: build canvas
        run: |
          cd Canvas
          ./gradlew applypatches
          ./gradlew createCanvasServer
          ./gradlew generateDevelopmentBundle --info

      # 构建leaf
      - name: build leaf
        run: |
          cd Leaf
          ./gradlew applypatches
          ./gradlew createReobfBundlerJar
          ./gradlew createMojmapBundlerJar

      # 构建leaves
      - name: build leaves
        run: |
          cd Leaves
          ./gradlew applypatches
          ./gradlew createReobfBundlerJar
          ./gradlew createMojmapBundlerJar

          
      # 归档paper
      - name: Upload Paper Artifacts 
        uses: actions/upload-artifact@v4
        with:
          name: Paper Artifact
          path: Paper/build/libs/*

      # 归档folia
      - name: Upload Folia Artifacts 
        uses: actions/upload-artifact@v4
        with:
          name: Folia Artifact
          path: Folia/build/libs/*

      # 归档pufferfish
      - name: Upload Pufferfish Artifacts 
        uses: actions/upload-artifact@v4
        with:
          name: Pufferfish Artifact
          path: Pufferfish/build/libs/*

      # 归档purpur
      - name: Upload Purpur Artifacts 
        uses: actions/upload-artifact@v4
        with:
          name: Purpur Artifact
          path: Purpur/build/libs/*

      # 归档canvas
      - name: Upload Canvas Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Canvas Artifact
          path: Canvas/build/libs/*

      # 归档leaf
      - name: Upload Leaf Artifacts 
        uses: actions/upload-artifact@v4
        with:
          name: Leaf Artifact
          path: Leaf/build/libs/*
          
      # 归档leaves
      - name: Upload Leaves Artifacts 
        uses: actions/upload-artifact@v4
        with:
          name: Leaves Artifact
          path: Leaves/build/libs/*
