# This is a basic workflow to help you get started with Actions

name: Spigot

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # 定时构建，每周二，四凌晨四点触发
  schedule:
    - cron: '0 4 * * 2,4'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # 设置java
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: |
              8
              11
              17
              21
      # 安装git（不太确定git有没有预装）
      # - name: install git
      #   run: su root && apt-get install git

      # 设置git名称和邮箱（虽然不是真的）
      #- name: setup git
      #  run: git config --global user.email "123@123.123" && git config --global user.name "123" && git config --global --unset core.autocrlf

      # 下载buildtools
      - name: download spigot buildtools
        run: curl -o BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

      # 创建输出目录
      - name: mkdir
        run: mkdir output
        
      # 构建spigot与craftbukkit
      - name: build spigot
        run: |
            java -Xmx4G -jar BuildTools.jar --o ./output
            java -Xmx4G -jar BuildTools.jar --compile craftbukkit --o ./output
          
      # 归档spigot
      - name: Upload Spigot Artifacts 
        uses: actions/upload-artifact@v4
        with:
          name: Spigot Artifact
          path: output/*.jar
